# -*- coding: utf-8 -*-
"""ACTIVIDAD1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mwRG3kq12eDDc9MF5WpWyHvyKimOJYNl
"""

!head data.tsv

!tail data.tsv #¿Cuántos pedidos parece haber?

!wc -l data.tsv  #¿Cuántas líneas hay en este archivo?

"""¿Qué burrito es más popular, steak o chicken?"""

!grep -i 'chicken burrito' data.tsv | wc -l ; grep -o -i 'steak burrito' data.tsv | wc -l

"""¿Los burritos de pollo suelen tener frijoles negros o frijoles pintos?

"""

!grep -o -i 'black beans' data.tsv | wc -l; grep -o -i 'pinto beans' data.tsv | wc -l

"""¿Los burritos de pollo suelen tener frijoles negros o frijoles pintos?"""

!grep -i 'chicken burrito' data.tsv | grep -o -i 'black beans' | wc -l; grep -i 'chicken burrito' data.tsv | grep -o -i 'pinto beans' | wc -l